
platform :ios, '13.0'

target 'Talula' do
  
  use_frameworks!

  pod 'SnapKit', '4.2.0' # creating UI in code

  target 'TalulaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
